# 1. Create a 3x3x3 array with random values


In [2]:
import numpy as np

random_3x3x3_array = np.random.rand(3, 3, 3)
random_3x3x3_array

array([[[0.23801126, 0.86510924, 0.33970646],
        [0.98526097, 0.23947794, 0.41977471],
        [0.70505826, 0.9889016 , 0.07083459]],

       [[0.05638966, 0.43350248, 0.84115595],
        [0.87946515, 0.82869407, 0.20323239],
        [0.26099803, 0.22079191, 0.34670016]],

       [[0.64843181, 0.13995362, 0.22264978],
        [0.51939175, 0.00968916, 0.08872153],
        [0.74233364, 0.09406741, 0.09873139]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [4]:
import numpy as np

diagonal_values = np.array([1, 2, 3, 4])
matrix_5x5 = np.diag(diagonal_values, k=-1)
matrix_5x5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern


In [6]:
import numpy as np

checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
checkerboard_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix


In [8]:
import numpy as np

random_5x5_matrix = np.random.rand(5, 5)
normalized_matrix = (random_5x5_matrix - random_5x5_matrix.min()) / (random_5x5_matrix.max() - random_5x5_matrix.min())
normalized_matrix

array([[0.02886146, 1.        , 0.75353943, 0.82644449, 0.01244158],
       [0.09071741, 0.36306159, 0.        , 0.05172636, 0.35845019],
       [0.90020122, 0.36545089, 0.50556637, 0.62535756, 0.54602653],
       [0.4218709 , 0.64387712, 0.29270483, 0.46572915, 0.53363417],
       [0.66927319, 0.26442948, 0.87783294, 0.42751492, 0.4770782 ]])

# 5. How to find common values between two arrays?


In [10]:
import numpy as np

array_A = np.array([1, 2, 3, 4, 5])
array_B = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array_A, array_B)
common_values

array([3, 4, 5])

# 6.How to get the dates of yesterday, today and tomorrow?


In [11]:
from datetime import datetime, timedelta

today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print(f"Yesterday: {yesterday.strftime('%Y-%m-%d')}")
print(f"Today: {today.strftime('%Y-%m-%d')}")
print(f"Tomorrow: {tomorrow.strftime('%Y-%m-%d')}")


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal



In [12]:
import numpy as np

array_A = np.array([1, 2, 3, 4, 5])
array_B = np.array([1, 2, 3, 4, 5])

are_equal = np.array_equal(array_A, array_B)
are_equal

True

# 8.Create a random vector of size 10 and replace the maximum value by 0:


In [16]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the maximum value in the vector
max_value = np.max(random_vector)

# Replace the maximum value with 0
random_vector[random_vector == max_value] = 0
random_vector
max_value

0.9422307934704692

# 9. How to print all the values of an array?


In [17]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)


[1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix



In [19]:
import numpy as np

# Create a sample matrix (replace this with your actual matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the mean of each row from the respective rows
matrix_centered = matrix - row_means
matrix_centered

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [21]:
import numpy as np
given_vector = np.array([1, 2, 3, 4, 5])
indices_to_add_1 = np.array([0, 2, 4])
mask = np.zeros_like(given_vector)
mask[indices_to_add_1] = 1
result_vector = given_vector + mask
result_vector

array([2, 2, 4, 4, 6])

# 12.How to get the diagonal of a dot product?


In [22]:
import numpy as np

matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

dot_product_result = np.dot(matrix_A, matrix_B)

diagonal_result = np.diagonal(dot_product_result)
diagonal_result

array([30, 69, 90])

# 13.How to find the most frequent value in an array?



In [23]:
import numpy as np

my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 5])
unique_values, counts = np.unique(my_array, return_counts=True)
most_frequent_index = np.argmax(counts)
most_frequent_value = unique_values[most_frequent_index]

print(f"The most frequent value in the array is {most_frequent_value} with {counts[most_frequent_index]} occurrences.")


The most frequent value in the array is 3 with 3 occurrences.


# 14.How to get the n largest value in the array

In [25]:
import heapq

def get_n_largest(arr, n):
    return heapq.nlargest(n, arr)

# Example usage:
my_array = [12, 34, 45, 9, 8, 76]
n = 1
n_largest_values = get_n_largest(my_array, n)
print(n_largest_values)  

[76]


# 15.How to create a record array from a regular array.


In [27]:
import numpy as np
regular_array = [(1, "vishal", 25), (2, "shiva", 30), (3, "sourav", 22)]
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]
record_array = np.array(regular_array, dtype=dtype)
print("First record:")
print("ID:", record_array[0]['ID'])
print("Name:", record_array[0]['Name'])
print("Age:", record_array[0]['Age'])
print("\nSecond record:")
print("ID:", record_array[1][0])
print("Name:", record_array[1][1])
print("Age:", record_array[1][2])

First record:
ID: 1
Name: vishal
Age: 25

Second record:
ID: 2
Name: shiva
Age: 30


# 16.How to swap two rows of an array.

In [28]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row1_index = 0  
row2_index = 2 
temp_row = np.copy(array[row1_index])
array[row1_index] = array[row2_index]
array[row2_index] = temp_row
print(array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17.Write python code to reshape  to the next dimenssion of numpy array.



In [29]:
import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = original_array.reshape((2, -1))

print("Original array:")
print(original_array)
print("Reshaped array:")
print(reshaped_array)

Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]
